/* WhistleChain frontend app logic (plain JS + ethers.js v6, no build step). */

const STAKE_TOKEN_DECIMALS = 18;

// UZH Ethereum Proof-of-Stake (PoS) test network
const UZH_ETH_POS = {
  chainId: "0x1123F", // 70207 in hex
  chainName: "UZH_ETH_PoS",
  nativeCurrency: { name: "UZHETHs", symbol: "UZHETHs", decimals: 18 },
  rpcUrls: ["https://rpc.uzheths.ifi.uzh.ch"],
  blockExplorerUrls: ["https://explorer.uzheths.ifi.uzh.ch"],
};

let provider, signer, signerAddress;
let contracts = {}; // { token, reputation, governance, treasury, registry } 
let addresses = {};

// Bootstrap: load ABIs + addresses generated by scripts/deploy.js
async function loadContractMeta() {
  addresses = await (await fetch("./contracts/addresses.json")).json();
  const abiNames = {
    token: "WhistleChainToken",
    reputation: "Reputation",
    governance: "Governance",
    treasury: "Treasury",
    registry: "ReportRegistry",
  };
  const abis = {};
  for (const [key, fileBase] of Object.entries(abiNames)) {
    abis[key] = await (await fetch(`./contracts/${fileBase}.abi.json`)).json();
  }
  return { abis, abiNames };
}

async function getReadProvider() {
  // Falls back to a public JSON-RPC provider pointed at whatever network
  // the deployment addresses were generated for, using window.ethereum if
  // present (read-only calls do not require the user's wallet to be unlocked).
  if (window.ethereum) {
    return new ethers.BrowserProvider(window.ethereum);
  }
  throw new Error("No injected wallet found. Install MetaMask or use a wallet-enabled browser.");
}

async function initContracts() {
  const { abis } = await loadContractMeta();
  const readProvider = provider || (await getReadProvider());
  contracts = {
    token: new ethers.Contract(addresses.WhistleChainToken, abis.token, signer || readProvider),
    reputation: new ethers.Contract(addresses.Reputation, abis.reputation, signer || readProvider),
    governance: new ethers.Contract(addresses.Governance, abis.governance, signer || readProvider),
    treasury: new ethers.Contract(addresses.Treasury, abis.treasury, signer || readProvider),
    registry: new ethers.Contract(addresses.ReportRegistry, abis.registry, signer || readProvider),
  };
}

function withSigner(contract) {
  if (!signer) throw new Error("Connect or generate a wallet first.");
  return contract.connect(signer);
}


// Wallet connection

document.getElementById("connectBtn").addEventListener("click", async () => {
  if (!window.ethereum) {
    alert("MetaMask (or another injected wallet) was not detected in this browser.");
    return;
  }
  provider = new ethers.BrowserProvider(window.ethereum);
  await provider.send("eth_requestAccounts", []);
  signer = await provider.getSigner();
  signerAddress = await signer.getAddress();
  const net = await provider.getNetwork();
  document.getElementById("networkBadge").textContent =
    `connected: ${signerAddress.slice(0, 6)}…${signerAddress.slice(-4)} (chainId ${net.chainId})`;
  await initContracts();
  await refreshValidatorReputation();
});

document.getElementById("addNetworkBtn").addEventListener("click", async () => {
  if (!window.ethereum) {
    alert("MetaMask (or another injected wallet) was not detected in this browser.");
    return;
  }
  try {
    await window.ethereum.request({
      method: "wallet_addEthereumChain",
      params: [UZH_ETH_POS],
    });
  } catch (err) {
    alert("Could not add the UZH_ETH_PoS network: " + (err.message || String(err)));
  }
});

document.getElementById("generateWalletBtn").addEventListener("click", async () => {
  // Generates a brand-new wallet in-browser, NOT linked to the user's
  // real-world identity by this app. The private key is shown once and
  // never transmitted anywhere; the user is responsible for saving it.
  // This wallet is connected to the same RPC endpoint as window.ethereum's
  // configured network so it can send transactions directly.
  const readProvider = await getReadProvider();
  const wallet = ethers.Wallet.createRandom().connect(readProvider);
  signer = wallet;
  signerAddress = wallet.address;
  document.getElementById("networkBadge").textContent =
    `fresh wallet: ${wallet.address.slice(0, 6)}…${wallet.address.slice(-4)}`;
  alert(
    "A new pseudonymous wallet was generated in your browser.\n\n" +
    `Address: ${wallet.address}\n` +
    `Private key: ${wallet.privateKey}\n\n` +
    "SAVE THIS PRIVATE KEY NOW — it is shown only once and is not stored anywhere. " +
    "You must fund this address with test ETH (for gas) and UZHETHs (for the stake) before submitting a report. " +
    "Remember: this wallet is pseudonymous, not fully anonymous — see the privacy note above."
  );
  await initContracts();
  document.getElementById("rWallet").value = wallet.address;
});


// Tabs

document.querySelectorAll(".tab-btn").forEach((btn) => {
  btn.addEventListener("click", () => {
    document.querySelectorAll(".tab-btn").forEach((b) => b.classList.remove("active"));
    document.querySelectorAll(".tab-panel").forEach((p) => p.classList.remove("active"));
    btn.classList.add("active");
    document.getElementById(`tab-${btn.dataset.tab}`).classList.add("active");
    if (btn.dataset.tab === "validator") loadReportList();
    if (btn.dataset.tab === "treasury") loadTreasuryView();
  });
});


// Whistleblower: submit report

document.getElementById("reportForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const statusEl = document.getElementById("submitStatus");
  try {
    if (!contracts.registry) await initContracts();
    if (!signer) throw new Error("Connect or generate a wallet first.");

    const title = document.getElementById("rTitle").value;
    const description = document.getElementById("rDescription").value;
    const category = document.getElementById("rCategory").value;
    const walletAddress = document.getElementById("rWallet").value.trim();
    const stakeHuman = document.getElementById("rStake").value;

    statusEl.textContent = "Hashing and encrypting report client-side...";

    const timestamp = new Date().toISOString();
    const canonical = canonicalizeReport({ title, description, category, timestamp });
    const reportHash = await sha256Hex(canonical);

    const encKey = await generateEncryptionKey();
    const { ciphertextHex, ivHex } = await encryptText(canonical, encKey);

    // Both reportHash and the encrypted ciphertext/IV are stored fully
    // on-chain by ReportRegistry (see contract NatSpec for the gas/size cap).
    const maxBytes = Number(await contracts.registry.MAX_ENCRYPTED_CONTENT_BYTES());
    const ciphertextByteLength = (ciphertextHex.length - 2) / 2;
    if (ciphertextByteLength > maxBytes) {
      throw new Error(
        `Encrypted report is ${ciphertextByteLength} bytes, which exceeds the on-chain limit of ` +
        `${maxBytes} bytes. Shorten the description and try again.`
      );
    }

    const stakeWei = ethers.parseUnits(stakeHuman, STAKE_TOKEN_DECIMALS);

    statusEl.textContent = "Approving stake transfer...";
    const tokenWithSigner = withSigner(contracts.token);
    const approveTx = await tokenWithSigner.approve(addresses.ReportRegistry, stakeWei);
    await approveTx.wait();

    statusEl.textContent = "Submitting report commitment + encrypted content on-chain...";
    const registryWithSigner = withSigner(contracts.registry);
    const tx = await registryWithSigner.submitReport(reportHash, ciphertextHex, ivHex, walletAddress, stakeWei);
    const receipt = await tx.wait();

    const submittedEvent = receipt.logs
      .map((log) => {
        try {
          return contracts.registry.interface.parseLog(log);
        } catch {
          return null;
        }
      })
      .find((e) => e && e.name === "ReportSubmitted");
    const reportId = submittedEvent ? submittedEvent.args.reportId.toString() : "(see tx)";

    statusEl.textContent =
      `Report submitted successfully.\n\n` +
      `Report ID: ${reportId}\n` +
      `On-chain SHA-256 commitment: ${reportHash}\n` +
      `Encrypted content and IV are now stored on-chain (${ciphertextByteLength} bytes ciphertext).\n\n` +
      `DECRYPTION KEY (share only out-of-band with the review committee, never on-chain):\n${encKey}\n\n` +
      `Tx hash: ${receipt.hash}`;
  } catch (err) {
    console.error(err);
    statusEl.textContent = "Error: " + (err.reason || err.message || String(err));
  }
});

 
// Validator: list reports, decrypt, vote, finalize
 
let selectedReportId = null;

document.getElementById("refreshReportsBtn").addEventListener("click", loadReportList);

async function loadReportList() {
  if (!contracts.registry) await initContracts();
  const listEl = document.getElementById("reportList");
  listEl.innerHTML = "Loading...";

  const filter = contracts.registry.filters.ReportSubmitted();
  const events = await contracts.registry.queryFilter(filter, 0, "latest");

  if (events.length === 0) {
    listEl.innerHTML = "<p class='small'>No reports submitted yet.</p>";
    return;
  }

  listEl.innerHTML = "";
  for (const ev of events.reverse()) {
    const reportId = ev.args.reportId.toString();
    const report = await contracts.registry.getReport(reportId);
    const summary = await contracts.governance.getVoteSummary(reportId);
    const stateNames = ["None", "Open", "Finalized"];
    const statusNames = ["Submitted", "Approved", "Rejected"];

    const contentBytes = (report.encryptedContent.length - 2) / 2;
    const div = document.createElement("div");
    div.className = "report-item";
    div.innerHTML = `
      <strong>Report #${reportId}</strong> — status: ${statusNames[report.status]}, vote: ${stateNames[summary.state]}<br/>
      <span class="meta">hash: ${report.reportHash}</span><br/>
      <span class="meta">encrypted content stored on-chain: ${contentBytes} bytes</span><br/>
      <span class="meta">stake: ${ethers.formatUnits(report.stakeAmount, STAKE_TOKEN_DECIMALS)} UZHETHs</span><br/>
      <span class="meta">approve weight: ${summary.approveWeight} / reject weight: ${summary.rejectWeight} / eligible: ${summary.eligibleWeight}</span><br/>
      <span class="meta">voting ends: ${summary.endTime > 0n ? new Date(Number(summary.endTime) * 1000).toLocaleString() : "-"}</span>
      <div class="row" style="margin-top:8px">
        <button data-report="${reportId}" class="review-btn">Review / Vote</button>
      </div>
    `;
    listEl.appendChild(div);
  }

  document.querySelectorAll(".review-btn").forEach((btn) => {
    btn.addEventListener("click", () => openDecryptPanel(btn.dataset.report));
  });
}

async function openDecryptPanel(reportId) {
  selectedReportId = reportId;
  document.getElementById("decryptPanel").style.display = "block";
  document.getElementById("decryptReportId").textContent = reportId;
  document.getElementById("decryptedContent").textContent = "";
  document.getElementById("voteStatus").textContent = "";
}

document.getElementById("decryptBtn").addEventListener("click", async () => {
  const key = document.getElementById("decryptKeyInput").value.trim();
  const outEl = document.getElementById("decryptedContent");
  try {
    // Both the ciphertext and its IV are read directly from contract
    // storage — no off-chain lookup is needed since the report content
    // itself lives on-chain.
    const report = await contracts.registry.getReport(selectedReportId);
    const plaintext = await decryptHex(report.encryptedContent, report.encryptionIv, key);
    // Verify the decrypted content matches the on-chain commitment.
    const recomputedHash = await sha256Hex(plaintext);
    const matches = recomputedHash.toLowerCase() === report.reportHash.toLowerCase();
    outEl.textContent =
      (matches ? "✔ Hash verified against on-chain commitment.\n\n" : "⚠ HASH MISMATCH — content may be tampered.\n\n") +
      plaintext;
  } catch (err) {
    outEl.textContent = "Decryption failed: " + (err.message || String(err));
  }
});

async function castVote(approve) {
  const statusEl = document.getElementById("voteStatus");
  try {
    if (!signer) throw new Error("Connect a validator wallet first.");
    const governanceWithSigner = withSigner(contracts.governance);
    const tx = await governanceWithSigner.castVote(selectedReportId, approve);
    statusEl.textContent = "Submitting vote...";
    await tx.wait();
    statusEl.textContent = `Vote (${approve ? "APPROVE" : "REJECT"}) recorded for report #${selectedReportId}.`;
    await loadReportList();
  } catch (err) {
    statusEl.textContent = "Error: " + (err.reason || err.message || String(err));
  }
}

document.getElementById("voteApproveBtn").addEventListener("click", () => castVote(true));
document.getElementById("voteRejectBtn").addEventListener("click", () => castVote(false));

document.getElementById("finalizeBtn").addEventListener("click", async () => {
  const statusEl = document.getElementById("voteStatus");
  try {
    if (!signer) throw new Error("Connect a wallet first (anyone may call finalize once voting ends).");
    const governanceWithSigner = withSigner(contracts.governance);
    const tx = await governanceWithSigner.finalizeVote(selectedReportId);
    statusEl.textContent = "Finalizing...";
    await tx.wait();
    statusEl.textContent = `Report #${selectedReportId} finalized.`;
    await loadReportList();
  } catch (err) {
    statusEl.textContent = "Error: " + (err.reason || err.message || String(err));
  }
});

document.getElementById("joinValidatorBtn").addEventListener("click", async () => {
  const statusEl = document.getElementById("joinValidatorStatus");
  try {
    if (!contracts.reputation) await initContracts();
    if (!signer) throw new Error("Connect or generate a wallet first.");

    const joinCost = await contracts.reputation.JOIN_COST();
    statusEl.textContent = "Approving 20 UZHETHs for the Reputation contract...";
    const tokenWithSigner = withSigner(contracts.token);
    await (await tokenWithSigner.approve(addresses.Reputation, joinCost)).wait();

    statusEl.textContent = "Joining as a validator (self-service, no approval needed)...";
    const reputationWithSigner = withSigner(contracts.reputation);
    const tx = await reputationWithSigner.joinAsValidator();
    await tx.wait();

    statusEl.textContent =
      "You are now a registered validator with 100 starting reputation. " +
      "Your first 5 votes will count at ramped power (20% -> 100%).";
    await refreshValidatorReputation();
  } catch (err) {
    statusEl.textContent = "Error: " + (err.reason || err.message || String(err));
  }
});

async function refreshValidatorReputation() {
  if (!signerAddress || !contracts.reputation) return;
  try {
    const isVal = await contracts.reputation.isValidator(signerAddress);
    if (!isVal) {
      document.getElementById("myReputation").textContent = "This wallet is not a registered validator.";
      return;
    }
    const rawWeight = await contracts.reputation.votingWeightOf(signerAddress);
    const [effectiveWeight, rampBps] = await contracts.governance.currentEffectiveWeight(signerAddress);
    const votesSoFar = await contracts.governance.lifetimeVotesCast(signerAddress);
    const probationVotes = await contracts.governance.PROBATION_VOTES();
    const rampPct = (Number(rampBps) / 100).toFixed(0);
    const probationNote =
      votesSoFar < probationVotes
        ? ` (probation: vote ${votesSoFar + 1n} of ${probationVotes}, currently ${rampPct}% voting power)`
        : " (probation complete: full voting power)";
    document.getElementById("myReputation").textContent =
      `Reputation: ${rawWeight} | effective voting weight for your next vote: ${effectiveWeight}${probationNote}`;
  } catch {
    /* ignore until contracts are initialized */
  }
}

 
// Treasury & Governance view
 
async function loadTreasuryView() {
  if (!contracts.treasury) await initContracts();

  const [bal, donated, forfeited, paidOut] = await Promise.all([
    contracts.treasury.balance(),
    contracts.treasury.totalDonated(),
    contracts.treasury.totalForfeited(),
    contracts.treasury.totalPaidOut(),
  ]);
  document.getElementById("treasuryBalance").textContent = ethers.formatUnits(bal, STAKE_TOKEN_DECIMALS);
  document.getElementById("totalDonated").textContent = ethers.formatUnits(donated, STAKE_TOKEN_DECIMALS);
  document.getElementById("totalForfeited").textContent = ethers.formatUnits(forfeited, STAKE_TOKEN_DECIMALS);
  document.getElementById("totalPaidOut").textContent = ethers.formatUnits(paidOut, STAKE_TOKEN_DECIMALS);

  // Validators
  const count = await contracts.governance.validatorCount();
  let validatorHtml = "<ul>";
  for (let i = 0; i < count; i++) {
    const addr = await contracts.governance.validatorList(i);
    const weight = await contracts.reputation.votingWeightOf(addr);
    const active = await contracts.reputation.isValidator(addr);
    validatorHtml += `<li>${addr} — reputation: ${weight} — ${active ? "active" : "deactivated"}</li>`;
  }
  validatorHtml += "</ul>";
  document.getElementById("validatorInfo").innerHTML = validatorHtml;

  // Outcomes
  const filter = contracts.registry.filters.ReportSettled();
  const events = await contracts.registry.queryFilter(filter, 0, "latest");
  let outcomesHtml = events.length ? "<ul>" : "<p class='small'>No settled reports yet.</p>";
  for (const ev of events.reverse()) {
    const { reportId, approved, rewardPaid, stakeReturned } = ev.args;
    outcomesHtml += `<li>Report #${reportId} — ${approved ? "APPROVED" : "REJECTED"}` +
      (approved
        ? ` — reward: ${ethers.formatUnits(rewardPaid, STAKE_TOKEN_DECIMALS)}  UZHETHs, stake returned: ${ethers.formatUnits(stakeReturned, STAKE_TOKEN_DECIMALS)}  UZHETHs`
        : ` — stake forfeited to treasury`) +
      `</li>`;
  }
  if (events.length) outcomesHtml += "</ul>";
  document.getElementById("outcomesList").innerHTML = outcomesHtml;
}

document.getElementById("donateBtn").addEventListener("click", async () => {
  const statusEl = document.getElementById("donateStatus");
  try {
    if (!signer) throw new Error("Connect a wallet first.");
    const amount = ethers.parseUnits(document.getElementById("donateAmount").value, STAKE_TOKEN_DECIMALS);
    const tokenWithSigner = withSigner(contracts.token);
    statusEl.textContent = "Approving donation...";
    await (await tokenWithSigner.approve(addresses.Treasury, amount)).wait();
    statusEl.textContent = "Donating...";
    const treasuryWithSigner = withSigner(contracts.treasury);
    await (await treasuryWithSigner.donate(amount)).wait();
    statusEl.textContent = "Donation recorded. Thank you!";
    await loadTreasuryView();
  } catch (err) {
    statusEl.textContent = "Error: " + (err.reason || err.message || String(err));
  }
});

 
// Initial load
 
(async () => {
  try {
    await initContracts();
  } catch (err) {
    console.warn("Contracts not yet initialized (connect a wallet):", err.message);
  }
})();
